/**
 * Room-code alphabet and helpers.
 *
 * The alphabet deliberately excludes characters that are easy to confuse when
 * read aloud or typed: 0/O, 1/I/L, and the ambiguous number/letter pairs. This
 * keeps six-character codes and invite links robust for humans.
 *
 * NOTE: this alphabet must stay in sync with the SQL `mp_gen_code()` function
 * in supabase/migrations — codes are generated on the server.
 */
export const ROOM_CODE_ALPHABET = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';

export const ROOM_CODE_LENGTH = 6;

const CODE_CHAR_SET = new Set(ROOM_CODE_ALPHABET.split(''));

/**
 * Normalise a raw room-code input for comparison/submission: trim surrounding
 * whitespace, strip any internal spaces/dashes, and uppercase. Common
 * lookalikes typed by users are folded to the canonical alphabet (o→0 is NOT
 * folded because 0 is not in the alphabet; instead O/o are dropped as invalid).
 */
export function normalizeRoomCode(raw: string): string {
  return raw
    .trim()
    .toUpperCase()
    .replace(/[\s-]+/g, '')
    .slice(0, ROOM_CODE_LENGTH);
}

/**
 * Whether a string is a valid, fully-formed room code: exactly
 * ROOM_CODE_LENGTH characters, all from the unambiguous alphabet.
 */
export function isValidRoomCode(code: string): boolean {
  if (code.length !== ROOM_CODE_LENGTH) return false;
  for (const ch of code) {
    if (!CODE_CHAR_SET.has(ch)) return false;
  }
  return true;
}

/**
 * Generate a random room code from the unambiguous alphabet. Used as a
 * client-side fallback/helper only — the authoritative code is generated by the
 * server RPC (which also guarantees uniqueness). An optional `rng` makes this
 * deterministic in tests.
 */
export function generateRoomCode(rng: () => number = Math.random): string {
  let out = '';
  for (let i = 0; i < ROOM_CODE_LENGTH; i++) {
    out += ROOM_CODE_ALPHABET[Math.floor(rng() * ROOM_CODE_ALPHABET.length)];
  }
  return out;
}
