/**
 * Human-readable rendering of a `DatasetAuditReport`.
 *
 * Kept separate from the audit itself so the numbers have exactly one source:
 * the Markdown report and the JSON artifact are two views of the same object,
 * and a formatting change can never silently alter a reported count.
 */

import type { DatasetAuditReport } from './datasetAudit';

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const head = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
  return rows.length > 0 ? `${head}\n${sep}\n${body}` : `${head}\n${sep}\n| _none_ |`;
}

function yesNo(value: boolean): string {
  return value ? 'yes' : 'NO';
}

/** Render the audit as Markdown suitable for committing to `docs/`. */
export function formatAuditMarkdown(report: DatasetAuditReport): string {
  const t = report.totals;
  const v = report.verdict;
  const lines: string[] = [];

  lines.push('# Location catalog audit');
  lines.push('');
  lines.push(
    'Generated by `npm run audit:dataset`. Do not edit by hand — regenerate it.',
  );
  lines.push('');
  lines.push(
    'A **canonical group** is one distinct *place*. Several catalog rows collapse ' +
      'into one group when they share an explicit group id, resolve to the same ' +
      'panorama, or sit within ' +
      `${report.thresholds.nearDuplicateKm} km of each other. Perceived variety is ` +
      'governed by group count, never by row count.',
  );
  lines.push('');

  // ── Verdict ─────────────────────────────────────────────────────────────
  lines.push('## Verdict');
  lines.push('');
  lines.push(
    `The catalog holds **${v.catalogGroups} canonical groups** in total, but a default ` +
      `game (${v.defaultDifficulty} difficulty, ${v.standardRoundCount} rounds) can only ` +
      `draw from **${v.defaultPoolGroups}** of them. Staying repeat-free across ` +
      `${v.targetFreshGames} consecutive games needs **${v.groupsRequired}**.`,
  );
  lines.push('');
  lines.push(
    `- Repeat-free consecutive standard games supported: **${v.freshGamesSupported}**`,
  );
  lines.push(`- Meets the freshness target: **${yesNo(v.sufficient)}**`);
  if (!v.sufficient) {
    lines.push(
      `- **Shortfall: ${v.groupsRequired - v.defaultPoolGroups} more canonical groups** ` +
        `at ${v.defaultDifficulty} difficulty are required before the selector alone can ` +
        'deliver the intended variety. No selection algorithm can invent places that are ' +
        'not in the catalog — see "Required catalog growth" below.',
    );
  }
  lines.push('');

  // ── Totals ──────────────────────────────────────────────────────────────
  lines.push('## Totals');
  lines.push('');
  lines.push(
    table(
      ['Metric', 'Value'],
      [
        ['Locations (rows)', String(t.locations)],
        ['Canonical groups (distinct places)', String(t.canonicalGroups)],
        ['Redundant rows (collapsed into another row)', String(t.redundantLocations)],
        ['Countries', String(t.countries)],
        ['Continents represented', String(t.continents)],
      ],
    ),
  );
  lines.push('');

  // ── Difficulty ──────────────────────────────────────────────────────────
  lines.push('## By difficulty');
  lines.push('');
  lines.push(
    table(
      ['Difficulty', 'Locations', 'Own groups'],
      report.byDifficulty.map((d) => [
        d.difficulty,
        String(d.locations),
        String(d.ownGroups),
      ]),
    ),
  );
  lines.push('');
  lines.push('### Pool sufficiency per round count');
  lines.push('');
  lines.push(
    'Groups counted the way real play sees them, i.e. after adjacent-difficulty ' +
      'fallback where the tier alone is too small.',
  );
  lines.push('');
  lines.push(
    table(
      ['Difficulty', 'Rounds', 'Groups', 'Playable', 'Comfortable', 'Shortfall', 'Used fallback'],
      report.byDifficulty.flatMap((d) =>
        d.sufficiency.map((s) => [
          d.difficulty,
          String(s.roundCount),
          String(s.groups),
          yesNo(s.playable),
          yesNo(s.comfortable),
          String(s.shortfall),
          yesNo(s.usedFallback),
        ]),
      ),
    ),
  );
  lines.push('');

  // ── Required growth ─────────────────────────────────────────────────────
  lines.push('### Required catalog growth');
  lines.push('');
  lines.push(
    `Target counts to make every offered round count comfortable — that is, ` +
      `${v.targetFreshGames} consecutive repeat-free games at each length. Counts are ` +
      '**canonical groups within the tier itself**, ignoring adjacent-difficulty ' +
      'fallback: relying on fallback to reach a target means the tier is not really ' +
      'that difficulty any more.',
  );
  lines.push('');
  const growthRows = report.byDifficulty.flatMap((d) =>
    d.sufficiency.map((s) => {
      const target = s.roundCount * v.targetFreshGames;
      return [
        d.difficulty,
        String(s.roundCount),
        String(d.ownGroups),
        String(target),
        String(Math.max(0, target - d.ownGroups)),
      ];
    }),
  );
  lines.push(
    table(['Difficulty', 'Rounds', 'Own groups now', 'Target', 'Must add'], growthRows),
  );
  lines.push('');

  // ── Geography ───────────────────────────────────────────────────────────
  lines.push('## By continent');
  lines.push('');
  lines.push(
    table(
      ['Continent', 'Locations', 'Groups'],
      report.byContinent.map((b) => [b.key, String(b.locations), String(b.groups)]),
    ),
  );
  lines.push('');
  lines.push('## By country');
  lines.push('');
  lines.push(
    table(
      ['Country', 'Locations', 'Groups'],
      report.byCountry.map((b) => [b.key, String(b.locations), String(b.groups)]),
    ),
  );
  lines.push('');

  // ── Collections ─────────────────────────────────────────────────────────
  lines.push('## By collection');
  lines.push('');
  lines.push(
    'A collection is **shippable** only when it can fill a standard game at least ' +
      'twice over. Unshippable collections stay defined in code but are not offered ' +
      'to players.',
  );
  lines.push('');
  lines.push(
    table(
      ['Collection', 'Locations', 'Groups', 'Easy', 'Normal', 'Hard', 'Shippable'],
      report.byCollection.map((c) => [
        c.collection,
        String(c.locations),
        String(c.groups),
        String(c.groupsByDifficulty.easy),
        String(c.groupsByDifficulty.normal),
        String(c.groupsByDifficulty.hard),
        yesNo(c.shippable),
      ]),
    ),
  );
  lines.push('');

  // ── Duplicates ──────────────────────────────────────────────────────────
  const d = report.duplicates;
  lines.push('## Duplicates and near-duplicates');
  lines.push('');
  lines.push(`- Duplicate location ids: **${d.duplicateLocationIds.length}**${
    d.duplicateLocationIds.length ? ` (${d.duplicateLocationIds.join(', ')})` : ''
  }`);
  lines.push(`- Duplicate panorama ids: **${d.duplicatePanoIds.length}**`);
  lines.push(`- Identical coordinate pairs: **${d.identicalCoordinates.length}**`);
  lines.push(`- Near-duplicate coordinate pairs: **${d.nearDuplicateCoordinates.length}**`);
  lines.push(`- Explicit location groups: **${d.explicitGroups.length}**`);
  lines.push('');
  if (d.nearDuplicateCoordinates.length > 0) {
    lines.push(
      table(
        ['Location A', 'Location B', 'Distance (km)'],
        d.nearDuplicateCoordinates.map((p) => [p.a, p.b, p.distanceKm.toFixed(3)]),
      ),
    );
    lines.push('');
  }

  // ── Clusters ────────────────────────────────────────────────────────────
  lines.push('## Small geographic clusters');
  lines.push('');
  lines.push(
    `Locations within ${report.thresholds.clusterKm} km of each other. These stay ` +
      'separate places for uniqueness; the in-match soft rules avoid serving two of ' +
      'them in one game.',
  );
  lines.push('');
  lines.push(
    table(
      ['Cluster', 'Members', 'Span (km)'],
      report.clusters.map((c) => [c.id, c.members.join(', '), c.spanKm.toFixed(1)]),
    ),
  );
  lines.push('');

  // ── Metadata issues ─────────────────────────────────────────────────────
  lines.push('## Metadata issues');
  lines.push('');
  lines.push(
    table(
      ['Location', 'Field', 'Issue'],
      report.metadataIssues.map((i) => [i.locationId, i.field, i.message]),
    ),
  );
  lines.push('');
  lines.push(`Audit clean: **${yesNo(report.ok)}**`);
  lines.push('');

  return lines.join('\n');
}
