/**
 * Build a verification input from catalog entries that have no verified
 * panorama — `npm run catalog:recheck-file`.
 *
 * The pre-V4 catalog was authored before the verification workflow existed, so
 * those entries carry no `panoId` and the `verification.streetView` gate cannot
 * pass while they remain. This turns them back into a batch file so the same
 * verification path can confirm their coverage.
 *
 * It writes an input only. It never modifies `src/data/locations.ts`, and it
 * deliberately omits any `panoId` — a panorama id may only come from a real
 * verification run, even for a location that has been playable for months.
 *
 * Fully offline. Regenerate whenever the catalog changes.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { LOCATIONS } from '../src/data/locations';

const outPath = resolve(process.cwd(), 'data/candidates/recheck-original-50.json');

const unverified = LOCATIONS.filter((l) => !l.panoId);

const file = {
  batch: 'recheck-original-50',
  notes:
    'GENERATED by scripts/make-recheck-batch.ts — do not hand-edit. These are ' +
    'EXISTING catalog entries that predate the verification workflow and carry ' +
    'no panoId. Verify with --recheck, which stops treating "already in the ' +
    'catalog" as an error; every other validation rule still applies. No panoId ' +
    'appears here: one may only come from a real verification run. Nothing in ' +
    'src/data/locations.ts is modified by generating or verifying this file.',
  candidates: unverified.map((l) => ({
    id: l.id,
    lat: l.lat,
    lng: l.lng,
    label: l.label,
    country: l.country,
    continent: l.continent,
    difficulty: l.difficulty,
    setting: l.setting,
    tags: l.tags ?? [],
    source: 'existing catalog entry, coverage not yet confirmed',
    rationale:
      'Recheck of a pre-V4 catalog entry. Confirming coverage is what moves ' +
      'verification.streetView off 50%.',
  })),
};

writeFileSync(outPath, `${JSON.stringify(file, null, 2)}\n`, 'utf8');
console.log(`Wrote ${outPath} with ${file.candidates.length} unverified catalog entries.`);
